import { ArrowDownRight, ArrowRight, ArrowUpRight, CheckCheck, Compass, Image, Layers3, MapPin, Network, ShieldCheck } from 'lucide-react'
import type { Observation } from '../../shared/domain'
import type { SceneSummary, SceneWorkspace } from '../api/client'
import { Badge, Button } from '../components/ui'
import { formatRelative } from '../utils/format'
import { SkyArt } from './SkyArt'

export function Overview({ scenes, scene, onSelect, onOpen, onIngest, onReview, onGraph }: {
  scenes: SceneSummary[]; scene: SceneWorkspace
  onSelect(id: string): void; onOpen(): void; onIngest(): void; onReview(observation?: Observation): void; onGraph(): void
}) {
  const totals = scenes.reduce((count, item) => ({ media: count.media + item.assetCount, findings: count.findings + item.observationCount, review: count.review + item.reviewCount }), {media:0, findings:0, review:0})
  const review = scene.observations.filter(item => item.requiresReview)
  return <div className="overview-page">
    <div className="overview-title"><div><span className="eyebrow">A LITTLE CLARITY GOES A LONG WAY</span><h1>Your world, in focus.</h1></div><span className="overview-date">{new Intl.DateTimeFormat('en', {month:'long',day:'numeric',year:'numeric'}).format(new Date())}</span></div>
    <section className="overview-hero">
      <div className="hero-copy"><span className="hero-label"><span/>SEE BEYOND THE FRAME</span><h2>Every scene.<br/>A clearer story.</h2><p>Connect the evidence.<br/>Discover what changed.</p><Button variant="primary" size="lg" onClick={onOpen}>Open workspace<ArrowUpRight size={19}/></Button><span className="hero-footnote"><Layers3 size={14}/>{scenes.length} {scenes.length === 1 ? 'scene' : 'scenes'}, ready to explore</span></div>
      <div className="hero-art"><SkyArt/><div className="hero-art-caption"><Compass size={19}/><span>A new point of view.</span><ArrowDownRight size={20}/></div><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/></div>
    </section>
    <section className="overview-stats" aria-label="Workspace statistics">{[{icon:Layers3,label:'Scenes',value:scenes.length},{icon:Image,label:'Media files',value:totals.media},{icon:Network,label:'Findings connected',value:totals.findings},{icon:ShieldCheck,label:'Awaiting review',value:totals.review}].map(item => <div key={item.label}><span className="stat-icon"><item.icon size={21}/></span><span><small>{item.label}</small><b>{String(item.value).padStart(2,'0')}</b></span>{item.label === 'Awaiting review' && <button onClick={() => onReview()} aria-label="Open review queue"><ArrowUpRight size={20}/></button>}</div>)}</section>
    <div className="overview-bottom"><section className="overview-scenes"><div className="section-title"><h2>Your scenes<span>{scenes.length}</span></h2><button onClick={onIngest}>Add media<ArrowUpRight size={15}/></button></div><div className="scene-card-grid">{scenes.map((item,index) => <button className="scene-card" key={item.id} onClick={() => onSelect(item.id)}><div className="scene-card-cover">{item.coverUrl ? <img src={item.coverUrl} alt={item.title} loading="lazy"/> : <SkyArt kind={index % 2 ? 'flight' : 'clouds'}/>}<span className="scene-card-index">SCENE {String(item.sequence).padStart(3,'0')}</span><span className="scene-card-open"><ArrowUpRight size={20}/></span></div><div className="scene-card-content"><span className="scene-card-location"><MapPin size={12}/>{item.locationLabel}</span><h3>{item.title}</h3><div className="scene-card-meta"><span>{item.assetCount} media<span>·</span>{item.observationCount} findings</span><Badge tone="blue">{item.reviewCount ? item.reviewCount + ' to review' : 'Reviewed'}</Badge></div></div></button>)}</div><button className="connections-card" onClick={onGraph}><span className="connections-icon"><Network size={25}/></span><span><b>Find the bigger picture.</b><small>Explore the connections in {scene.title}.</small></span><ArrowRight size={22}/><SkyArt kind="flight"/></button></section>
    <section className="overview-review"><div className="section-title"><h2>Needs a closer look</h2><ShieldCheck size={18}/></div><p className="review-context">{scene.title}</p><div className="overview-review-list">{review.slice(0,3).map((item,index) => <button key={item.id} onClick={() => onReview(item)}><span className="review-number">{String(index+1).padStart(2,'0')}</span><span><small>{item.lensId} · {Math.round(item.confidence*100)}% confidence</small><b>{item.label}</b><em>{formatRelative(item.updatedAt)}</em></span><ArrowUpRight size={16}/></button>)}{review.length === 0 && <div className="review-clear"><CheckCheck size={28}/><b>All caught up.</b><span>No pending findings in this scene.</span></div>}</div>{review.length > 0 && <Button variant="secondary" onClick={() => onReview()}>Review findings<ArrowRight size={16}/></Button>}<div className="review-art"><SkyArt kind="clouds"/><span>A clearer view starts<br/>with a closer look.</span></div></section></div>
    <footer className="overview-footer"><span>SCENARA</span><span>Less noise. More perspective.</span><span>Built around the evidence<ArrowUpRight size={12}/></span></footer>
  </div>
}
