import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import type {
  CaptureContext,
  ObservationFieldDefinition,
  ObservationKnowledgeCatalog,
  ObservationKnowledgeRule,
  PolicyProfile,
  TemporalMode,
} from '../shared/knowledge'
import type { LensId } from '../shared/domain'
import type { ObservationSeverity } from '../shared/knowledge'

interface ConceptSeed {
  id: string
  label: string
  category: string
  lens: LensId
  aliases: string[]
  contexts: CaptureContext[]
  cues: string[]
  exclusions: string[]
  attributes: string[]
  action: string
  risk: ObservationSeverity
}

const streetContexts: CaptureContext[] = ['streetscape','intersection','sidewalk','transit','building_edge']
const greenContexts: CaptureContext[] = ['park','waterfront','streetscape','sidewalk']
const workContexts: CaptureContext[] = ['construction','streetscape','intersection','sidewalk']

const concepts: ConceptSeed[] = [
  {id:'temporary_barrier',label:'Temporary curb barrier',category:'temporary_obstruction',lens:'general',aliases:['road barrier','orange barrier','barricade'],contexts:workContexts,cues:['portable barrier','high-visibility plastic','temporary placement'],exclusions:['permanent guardrail','painted curb'],attributes:['material','color','blocks_path','ownership_marking'],action:'Confirm ownership and restore the intended clear route.',risk:'medium'},
  {id:'traffic_cone',label:'Traffic cone cluster',category:'temporary_obstruction',lens:'safety',aliases:['cones','channelizer','road cone'],contexts:workContexts,cues:['conical marker','reflective collar','temporary grouping'],exclusions:['bollard','delineator post'],attributes:['count','spacing','reflective','blocks_path'],action:'Verify channelization and accessible detour continuity.',risk:'medium'},
  {id:'sidewalk_closure',label:'Sidewalk closure',category:'route_continuity',lens:'accessibility',aliases:['walkway closed','pedestrian closure','footpath closure'],contexts:workContexts,cues:['closure sign','continuous barricade','pedestrian diversion'],exclusions:['partial narrowing','private walkway'],attributes:['detour_present','detour_width_m','signage_present','duration_estimate'],action:'Provide a continuous, signed, accessible alternate route.',risk:'high'},
  {id:'clear_path_narrowing',label:'Clear path narrowing',category:'route_continuity',lens:'accessibility',aliases:['narrow sidewalk','reduced clear width','pinch point'],contexts:streetContexts,cues:['obstacle intrudes into route','restricted passing space','edge-to-edge pinch point'],exclusions:['perspective compression','temporary pedestrian'],attributes:['estimated_width_m','cause','length_m','passing_space_nearby'],action:'Measure the clear width and remove or relocate the obstruction.',risk:'high'},
  {id:'surface_crack',label:'Walking surface crack',category:'surface_condition',lens:'safety',aliases:['pavement crack','sidewalk crack','fissure'],contexts:streetContexts,cues:['linear surface separation','visible depth','broken edge'],exclusions:['control joint','decorative scoring'],attributes:['estimated_width_mm','estimated_depth_mm','length_m','active_displacement'],action:'Inspect displacement and schedule an appropriate surface repair.',risk:'medium'},
  {id:'vertical_displacement',label:'Vertical surface displacement',category:'surface_condition',lens:'accessibility',aliases:['trip edge','raised slab','uneven sidewalk'],contexts:streetContexts,cues:['adjacent surfaces at different heights','shadowed step edge','heaved slab'],exclusions:['intentional curb','stair tread'],attributes:['estimated_height_mm','edge_length_m','cause','route_position'],action:'Measure the level change and repair or bevel the transition.',risk:'high'},
  {id:'pothole',label:'Pothole',category:'surface_condition',lens:'safety',aliases:['road hole','pavement cavity','surface failure'],contexts:['streetscape','intersection','construction'],cues:['irregular pavement cavity','exposed aggregate','broken asphalt edge'],exclusions:['utility access cover','planned excavation'],attributes:['diameter_m','depth_mm','lane_position','water_filled'],action:'Mark the hazard and schedule pavement repair.',risk:'high'},
  {id:'standing_water',label:'Standing water',category:'drainage',lens:'environment',aliases:['ponding','water pooling','puddle'],contexts:['streetscape','intersection','sidewalk','park','waterfront'],cues:['reflective pooled water','waterline at low point','blocked flow path'],exclusions:['active rainfall sheen','decorative water feature'],attributes:['area_m2','estimated_depth_mm','blocks_route','likely_source'],action:'Inspect drainage inlets and restore positive drainage.',risk:'medium'},
  {id:'blocked_drain',label:'Blocked drainage inlet',category:'drainage',lens:'environment',aliases:['clogged drain','blocked catch basin','covered inlet'],contexts:['streetscape','intersection','park','waterfront'],cues:['debris over grate','sediment at inlet','ponding upstream'],exclusions:['sealed utility cover','decorative grate'],attributes:['blockage_percent','debris_type','ponding_present','inlet_type'],action:'Clear the inlet and inspect the downstream drainage path.',risk:'high'},
  {id:'curb_ramp',label:'Curb ramp',category:'accessible_crossing',lens:'accessibility',aliases:['kerb ramp','dropped curb','wheelchair ramp'],contexts:['intersection','sidewalk','streetscape'],cues:['sloped transition','curb cut','landing at crossing'],exclusions:['driveway apron','drainage channel'],attributes:['estimated_slope_percent','landing_present','aligned_to_crossing','surface_condition'],action:'Verify running slope, landing, alignment, and clear width.',risk:'medium'},
  {id:'tactile_warning',label:'Tactile warning surface',category:'accessible_crossing',lens:'accessibility',aliases:['detectable warning','truncated domes','tactile paving'],contexts:['intersection','sidewalk','transit'],cues:['regular dome pattern','contrasting panel','crossing edge placement'],exclusions:['decorative pavers','drainage mat'],attributes:['contrast','coverage_width_m','damaged_percent','alignment'],action:'Inspect coverage, contrast, alignment, and surface integrity.',risk:'medium'},
  {id:'missing_tactile_warning',label:'Missing tactile warning',category:'accessible_crossing',lens:'accessibility',aliases:['no detectable warning','missing tactile paving'],contexts:['intersection','sidewalk','transit'],cues:['curb ramp without dome panel','platform edge without warning strip'],exclusions:['crossing without level change','private non-public route'],attributes:['location_type','edge_exposure','ramp_present','confidence_basis'],action:'Confirm applicability and install a compliant detectable warning surface.',risk:'high'},
  {id:'crosswalk_marking',label:'Marked crosswalk',category:'crossing_visibility',lens:'safety',aliases:['zebra crossing','pedestrian crossing lines','crosswalk paint'],contexts:['intersection','streetscape'],cues:['parallel road markings','ladder bars','crossing boundary lines'],exclusions:['stop bar','lane divider'],attributes:['visibility_percent','marking_style','missing_segments','surface_wet'],action:'Record visibility and renew markings when maintenance thresholds are met.',risk:'medium'},
  {id:'crosswalk_fading',label:'Faded crosswalk marking',category:'crossing_visibility',lens:'safety',aliases:['worn crossing','faded zebra lines','crosswalk wear'],contexts:['intersection','streetscape'],cues:['patchy marking','aggregate visible through paint','low contrast'],exclusions:['shadow','wet pavement reflection'],attributes:['visibility_percent','wear_pattern','affected_area_percent','lighting'],action:'Schedule marking renewal and verify nighttime conspicuity.',risk:'high'},
  {id:'stop_line',label:'Stop line marking',category:'traffic_control',lens:'safety',aliases:['stop bar','limit line','halt line'],contexts:['intersection'],cues:['wide transverse road marking','approach-side position','adjacent stop control'],exclusions:['crosswalk boundary','speed table edge'],attributes:['visibility_percent','setback_m','aligned','obstructed'],action:'Verify placement and renew the marking if visibility is inadequate.',risk:'medium'},
  {id:'sign_obstruction',label:'Obstructed traffic sign',category:'traffic_control',lens:'safety',aliases:['hidden sign','covered sign','blocked road sign'],contexts:streetContexts,cues:['foliage in front of sign','object blocks sign face','partial sign visibility'],exclusions:['rear of sign','temporary cover for inactive sign'],attributes:['sign_type','visible_percent','obstruction_type','approach_direction'],action:'Restore the sign sightline and verify approach visibility.',risk:'high'},
  {id:'sign_damage',label:'Damaged traffic sign',category:'traffic_control',lens:'safety',aliases:['bent sign','broken sign','defaced sign'],contexts:streetContexts,cues:['bent panel','missing face','impact damage','illegible marking'],exclusions:['intentional blank back','temporary sign mounting'],attributes:['damage_type','legibility_percent','support_condition','reflectivity_concern'],action:'Replace or repair the sign and verify mounting integrity.',risk:'high'},
  {id:'signal_outage',label:'Traffic signal outage indicator',category:'traffic_control',lens:'safety',aliases:['dark signal','signal not working','traffic light outage'],contexts:['intersection'],cues:['all signal heads dark','temporary control present','conflicting traffic behavior'],exclusions:['unlit rear-facing head','captured between refresh cycles'],attributes:['heads_observed','backup_control','time_observed','corroborated'],action:'Escalate immediately and confirm the condition through multiple frames.',risk:'critical'},
  {id:'pedestrian_signal',label:'Pedestrian signal',category:'traffic_control',lens:'accessibility',aliases:['walk signal','ped signal','crossing signal'],contexts:['intersection'],cues:['walk/don’t-walk display','pushbutton relationship','crossing alignment'],exclusions:['vehicle signal','advertising display'],attributes:['display_state','countdown_visible','audible_feature','aligned_crossing'],action:'Verify operation, visibility, timing, and accessible features.',risk:'medium'},
  {id:'pushbutton_reach',label:'Pedestrian pushbutton reach',category:'accessible_crossing',lens:'accessibility',aliases:['crossing button access','push button reachability'],contexts:['intersection','sidewalk'],cues:['pushbutton at curb ramp','clear floor space','reachable pole face'],exclusions:['vehicle detector','private door button'],attributes:['estimated_height_m','clear_space','obstructed','directional_arrow'],action:'Measure reach range and ensure an unobstructed clear approach.',risk:'high'},
  {id:'missing_handrail',label:'Missing handrail',category:'vertical_circulation',lens:'accessibility',aliases:['no railing','stairs without rail','ramp rail missing'],contexts:['sidewalk','park','transit','building_edge'],cues:['open stair or ramp edge','mounting points without rail','long grade change'],exclusions:['single flush transition','landscape curb'],attributes:['route_type','rise_m','open_side','rail_other_side'],action:'Confirm applicability and provide continuous graspable support.',risk:'high'},
  {id:'handrail_damage',label:'Damaged handrail',category:'vertical_circulation',lens:'safety',aliases:['broken railing','loose handrail','bent rail'],contexts:['sidewalk','park','transit','building_edge'],cues:['disconnected rail','bent support','missing segment','sharp edge'],exclusions:['intentional termination','decorative offset'],attributes:['damage_type','affected_length_m','loose','sharp_edge'],action:'Restrict the hazard if necessary and repair the handrail.',risk:'high'},
  {id:'stair_edge_visibility',label:'Low-visibility stair edge',category:'vertical_circulation',lens:'accessibility',aliases:['unmarked nosing','poor stair contrast','hidden step edge'],contexts:['park','transit','building_edge','sidewalk'],cues:['uniform tread color','shadow obscures nosing','worn contrast strip'],exclusions:['level paving joints','decorative banding'],attributes:['contrast_present','lighting','wear_percent','step_count'],action:'Improve edge contrast and verify lighting across the full stair run.',risk:'high'},
  {id:'guardrail_gap',label:'Guardrail protection gap',category:'fall_protection',lens:'safety',aliases:['missing guardrail','open edge','barrier gap'],contexts:['park','waterfront','transit','building_edge','construction'],cues:['accessible elevated edge','interrupted rail','fall exposure'],exclusions:['ground-level planting edge','controlled access area'],attributes:['estimated_drop_m','gap_width_m','public_access','temporary_control'],action:'Secure the edge and restore continuous fall protection.',risk:'critical'},
  {id:'utility_pole',label:'Utility pole',category:'fixed_infrastructure',lens:'general',aliases:['power pole','telecom pole','wood pole'],contexts:streetContexts,cues:['vertical utility support','overhead wires','service attachments'],exclusions:['tree trunk','light pole without utilities'],attributes:['material','lean_estimate_deg','attachments','base_condition'],action:'Maintain entity identity across captures and inspect abnormal changes.',risk:'low'},
  {id:'pole_lean',label:'Leaning utility pole',category:'fixed_infrastructure',lens:'safety',aliases:['tilted pole','unstable utility pole'],contexts:streetContexts,cues:['pole axis deviates from vertical','disturbed base','wire tension asymmetry'],exclusions:['camera perspective','intentionally raked mast'],attributes:['lean_estimate_deg','lean_direction','base_damage','wire_tension_visible'],action:'Escalate for structural inspection and compare against prior captures.',risk:'high'},
  {id:'exposed_wire',label:'Exposed wire or cable',category:'electrical_hazard',lens:'safety',aliases:['loose cable','dangling wire','open wiring'],contexts:streetContexts,cues:['cable within reach','damaged sheath','unsecured loop'],exclusions:['properly supported aerial cable','decorative lighting cord'],attributes:['height_m','within_reach','sheath_damaged','energized_unknown'],action:'Isolate the area and refer the condition to the responsible utility.',risk:'critical'},
  {id:'open_utility_cover',label:'Open utility access',category:'surface_hazard',lens:'safety',aliases:['open manhole','missing cover','utility pit'],contexts:['streetscape','intersection','sidewalk','park'],cues:['uncovered access opening','displaced cover','visible chamber'],exclusions:['planned guarded excavation','drain inlet'],attributes:['opening_width_m','guarded','depth_visible','route_position'],action:'Guard the opening immediately and notify the responsible owner.',risk:'critical'},
  {id:'utility_cover_damage',label:'Damaged utility cover',category:'surface_hazard',lens:'safety',aliases:['broken manhole cover','cracked utility lid','loose cover'],contexts:['streetscape','intersection','sidewalk','park'],cues:['fracture','missing segment','rocking alignment','sunken frame'],exclusions:['surface staining','manufacturing texture'],attributes:['damage_type','level_difference_mm','traffic_exposure','loose'],action:'Inspect load capacity and replace or reset the cover.',risk:'high'},
  {id:'streetlight_outage',label:'Streetlight outage indicator',category:'lighting',lens:'safety',aliases:['dark streetlight','lamp out','lighting failure'],contexts:streetContexts,cues:['one fixture dark among lit peers','night capture','localized dark zone'],exclusions:['daylight capture','scheduled dimming','decorative unlit pole'],attributes:['capture_darkness','peer_lights_on','fixture_count','corroborated'],action:'Confirm after dark and submit the fixture for maintenance.',risk:'medium'},
  {id:'low_illumination',label:'Low pedestrian illumination',category:'lighting',lens:'safety',aliases:['dark sidewalk','poor lighting','low light level'],contexts:['sidewalk','park','transit','building_edge'],cues:['deep route shadows','uneven illumination','faces and edges indistinct'],exclusions:['camera underexposure','day-to-night transition'],attributes:['estimated_lux_band','uniformity','route_length_m','camera_exposure_known'],action:'Measure lighting on site and improve coverage and uniformity.',risk:'high'},
  {id:'tree_canopy',label:'Tree canopy coverage',category:'urban_ecology',lens:'environment',aliases:['shade tree','street tree canopy','tree cover'],contexts:greenContexts,cues:['mature crown','leaf coverage over public realm','tree shadow'],exclusions:['building shadow','temporary awning'],attributes:['coverage_percent','species_unknown','health_state','shade_route_percent'],action:'Track canopy coverage and preserve healthy shade infrastructure.',risk:'low'},
  {id:'tree_damage',label:'Damaged street tree',category:'urban_ecology',lens:'environment',aliases:['broken tree','split branch','tree wound'],contexts:greenContexts,cues:['broken limb','trunk wound','split union','uprooting'],exclusions:['routine pruning cut','naturally shed small twig'],attributes:['damage_type','limb_diameter_cm','fall_path','tree_health'],action:'Arrange an arborist inspection and protect the fall zone if needed.',risk:'high'},
  {id:'tree_grate_obstruction',label:'Tree grate obstruction',category:'urban_ecology',lens:'accessibility',aliases:['blocked tree pit','raised grate','tree well hazard'],contexts:['streetscape','sidewalk','park'],cues:['grate lifted by roots','debris-filled opening','route level change'],exclusions:['flush planted tree pit','intentional guard'],attributes:['level_difference_mm','opening_width_mm','route_intrusion','debris_percent'],action:'Restore a flush, stable walking surface while protecting the tree.',risk:'medium'},
  {id:'overgrown_vegetation',label:'Overgrown vegetation',category:'vegetation_management',lens:'environment',aliases:['encroaching plants','overgrown hedge','vegetation obstruction'],contexts:greenContexts,cues:['foliage intrudes into route','sightline blocked','sign obscured'],exclusions:['intentional planting bed','temporary seasonal display'],attributes:['intrusion_m','blocks_route','blocks_sightline','plant_type'],action:'Trim vegetation while retaining ecological value and required clearances.',risk:'medium'},
  {id:'dead_vegetation',label:'Dead or stressed vegetation',category:'vegetation_management',lens:'environment',aliases:['dead planting','brown vegetation','plant stress'],contexts:greenContexts,cues:['leaf loss out of season','brown canopy','bare planting patch'],exclusions:['deciduous dormancy','recently mulched bed'],attributes:['affected_percent','irrigation_indicator','season','species_unknown'],action:'Verify seasonal context, irrigation performance, and replacement need.',risk:'low'},
  {id:'erosion',label:'Soil erosion',category:'landscape_condition',lens:'environment',aliases:['washed soil','eroded bank','soil loss'],contexts:['park','waterfront','construction','streetscape'],cues:['rills','exposed roots','sediment fan','undercut edge'],exclusions:['planned swale','freshly graded protected soil'],attributes:['area_m2','depth_mm','active_runoff_path','sediment_destination'],action:'Stabilize the source, redirect erosive flow, and remove deposited sediment.',risk:'high'},
  {id:'sediment_runoff',label:'Sediment runoff',category:'water_quality',lens:'environment',aliases:['muddy runoff','silt discharge','construction sediment'],contexts:['construction','waterfront','streetscape'],cues:['turbid flow','sediment trail','failed inlet protection'],exclusions:['clean stormwater','decorative colored aggregate'],attributes:['source','receiving_area','control_present','extent_m'],action:'Contain the discharge and repair source controls before the next runoff event.',risk:'high'},
  {id:'oil_sheen',label:'Possible oil sheen',category:'water_quality',lens:'environment',aliases:['fuel sheen','rainbow slick','hydrocarbon film'],contexts:['streetscape','construction','waterfront'],cues:['iridescent surface film','localized source trail','rainbow refraction'],exclusions:['biological sheen','thin-film reflection artifact'],attributes:['area_m2','source_visible','water_body_connected','confidence_basis'],action:'Confirm in person, contain the source, and follow spill response procedures.',risk:'critical'},
  {id:'litter_accumulation',label:'Litter accumulation',category:'cleanliness',lens:'environment',aliases:['trash buildup','debris accumulation','street litter'],contexts:['streetscape','sidewalk','park','waterfront','transit'],cues:['multiple discarded items','concentrated debris','overflow near receptacle'],exclusions:['organized material staging','single incidental item'],attributes:['item_count_band','area_m2','hazardous_items','near_drain'],action:'Remove litter and investigate recurring accumulation sources.',risk:'low'},
  {id:'overflowing_bin',label:'Overflowing waste receptacle',category:'cleanliness',lens:'environment',aliases:['full trash bin','waste overflow','overfilled receptacle'],contexts:['streetscape','sidewalk','park','transit'],cues:['waste above rim','items surrounding bin','lid cannot close'],exclusions:['bagged collection awaiting pickup','construction skip'],attributes:['overflow_percent','ground_litter','leakage','pest_indicator'],action:'Service the receptacle and adjust collection frequency if recurring.',risk:'medium'},
  {id:'graffiti',label:'Graffiti or surface marking',category:'surface_management',lens:'general',aliases:['tagging','unauthorized marking','spray paint'],contexts:streetContexts,cues:['painted lettering','marker tag','surface defacement'],exclusions:['commissioned mural','official wayfinding','construction marking'],attributes:['surface','area_m2','offensive_content','recurring_location'],action:'Classify the marking and route it through the appropriate maintenance policy.',risk:'low'},
  {id:'wayfinding_sign',label:'Wayfinding sign',category:'information_access',lens:'accessibility',aliases:['direction sign','navigation signage','information sign'],contexts:['streetscape','sidewalk','park','transit','building_edge'],cues:['directional arrows','destination names','map panel'],exclusions:['traffic regulatory sign','advertising'],attributes:['legibility','contrast','viewing_height_m','languages'],action:'Verify legibility, contrast, placement, and route continuity.',risk:'low'},
  {id:'illegible_information',label:'Illegible public information',category:'information_access',lens:'accessibility',aliases:['unreadable sign','faded information','small text sign'],contexts:['streetscape','sidewalk','park','transit','building_edge'],cues:['low contrast text','surface wear','obscured instructions'],exclusions:['intentionally blank panel','distant unrelated sign'],attributes:['legibility_percent','cause','critical_message','alternate_format'],action:'Restore legibility and provide an accessible equivalent where appropriate.',risk:'high'},
  {id:'bench',label:'Public bench',category:'public_amenity',lens:'general',aliases:['street seat','park bench','public seating'],contexts:['streetscape','sidewalk','park','waterfront','transit'],cues:['fixed public seat','back or arm rests','resting area'],exclusions:['private café chair','retaining wall'],attributes:['seat_count','backrest','armrest','clear_space_adjacent'],action:'Track condition and accessible companion space over time.',risk:'low'},
  {id:'bench_damage',label:'Damaged public seating',category:'public_amenity',lens:'safety',aliases:['broken bench','damaged seat','unsafe seating'],contexts:['streetscape','sidewalk','park','waterfront','transit'],cues:['broken slat','sharp edge','unstable support','missing fastener'],exclusions:['normal wear','intentional segmented design'],attributes:['damage_type','usable_seats','sharp_edge','unstable'],action:'Restrict unsafe seating and repair or replace damaged components.',risk:'medium'},
  {id:'bike_rack',label:'Bicycle rack',category:'mobility_amenity',lens:'general',aliases:['cycle rack','bike parking','bicycle stand'],contexts:['streetscape','sidewalk','park','transit','building_edge'],cues:['fixed locking frame','multiple bicycle positions','anchored rack'],exclusions:['temporary fence','shopping cart rail'],attributes:['capacity','occupied_count','anchored','route_intrusion'],action:'Track capacity, utilization, anchorage, and route clearance.',risk:'low'},
  {id:'bike_lane_obstruction',label:'Bicycle lane obstruction',category:'mobility_route',lens:'safety',aliases:['blocked bike lane','cycle path obstruction','vehicle in bike lane'],contexts:['streetscape','intersection'],cues:['object within marked bicycle facility','forced merge condition','blocked buffer'],exclusions:['authorized work zone with detour','moving road user'],attributes:['obstruction_type','blocked_percent','detour_present','duration_unknown'],action:'Remove the obstruction or provide protected temporary routing.',risk:'high'},
  {id:'bollard',label:'Bollard',category:'fixed_infrastructure',lens:'general',aliases:['protective post','traffic bollard','security post'],contexts:streetContexts,cues:['short vertical post','repeated protective alignment','vehicle restriction'],exclusions:['traffic cone','utility marker'],attributes:['material','spacing_m','reflective','damaged'],action:'Track spacing, visibility, damage, and accessible route clearance.',risk:'low'},
  {id:'bollard_damage',label:'Damaged bollard',category:'fixed_infrastructure',lens:'safety',aliases:['bent bollard','broken post','loose bollard'],contexts:streetContexts,cues:['tilted post','impact damage','exposed base','missing cap'],exclusions:['flexible post deflection','intentional removable socket'],attributes:['damage_type','lean_deg','sharp_edge','base_exposed'],action:'Repair the bollard and check for hidden anchorage damage.',risk:'medium'},
  {id:'fire_hydrant_clearance',label:'Fire hydrant clearance',category:'emergency_access',lens:'safety',aliases:['blocked hydrant','hydrant obstruction','fire access'],contexts:['streetscape','sidewalk','building_edge'],cues:['object immediately around hydrant','vegetation covers fittings','access side blocked'],exclusions:['approved protective bollards','distant street furniture'],attributes:['clearance_m','obstruction_type','hydrant_visible','vehicle_access'],action:'Restore visibility and operational clearance for emergency access.',risk:'high'},
  {id:'emergency_exit_obstruction',label:'Emergency exit obstruction',category:'emergency_access',lens:'safety',aliases:['blocked exit','fire exit obstruction','egress blocked'],contexts:['building_edge','construction','transit'],cues:['objects at exit door','route narrowed by storage','gate prevents egress'],exclusions:['inactive façade door','secured non-egress door'],attributes:['exit_marked','obstruction_type','clear_width_m','door_operation_visible'],action:'Remove the obstruction immediately and verify the full egress route.',risk:'critical'},
  {id:'construction_fence',label:'Construction perimeter fence',category:'work_zone',lens:'general',aliases:['site fence','temporary fencing','work zone barrier'],contexts:workContexts,cues:['temporary mesh panels','site screening','weighted fence feet'],exclusions:['permanent property fence','event barricade'],attributes:['continuous','height_m','base_stable','view_obstruction'],action:'Track perimeter continuity, stability, and public-route impacts.',risk:'low'},
  {id:'unstable_fence',label:'Unstable temporary fence',category:'work_zone',lens:'safety',aliases:['leaning fence','loose construction fence','fallen panel'],contexts:workContexts,cues:['leaning panel','missing base weight','open connection','wind loading'],exclusions:['intentional gate opening','perspective distortion'],attributes:['lean_deg','base_weight_present','panel_gap_m','public_exposure'],action:'Stabilize the fence and secure all panel connections.',risk:'high'},
  {id:'excavation',label:'Open excavation',category:'work_zone',lens:'safety',aliases:['trench','construction pit','open dig'],contexts:workContexts,cues:['exposed cut earth','below-grade work','excavation edge'],exclusions:['shallow planting bed','covered utility access'],attributes:['estimated_depth_m','guarded','setback_m','water_present'],action:'Verify edge protection, access control, and excavation stability.',risk:'critical'},
  {id:'work_zone_signage',label:'Work-zone signage',category:'work_zone',lens:'safety',aliases:['construction sign','temporary warning sign','road work sign'],contexts:workContexts,cues:['temporary warning legend','portable sign support','advance notice'],exclusions:['permanent traffic sign','advertising board'],attributes:['message','legibility','orientation','advance_distance_m'],action:'Verify sequence, orientation, legibility, and advance placement.',risk:'medium'},
  {id:'accessible_detour',label:'Accessible temporary detour',category:'work_zone',lens:'accessibility',aliases:['pedestrian detour','temporary accessible route','work zone bypass'],contexts:workContexts,cues:['continuous protected route','temporary ramp','signed diversion'],exclusions:['vehicle-only diversion','informal desire path'],attributes:['clear_width_m','surface_stable','slope_percent','signage_present'],action:'Verify continuity, width, surface stability, slopes, and detectable edges.',risk:'high'},
  {id:'bus_stop',label:'Transit stop',category:'transit_access',lens:'general',aliases:['bus stop','transit boarding point','stop pole'],contexts:['transit','streetscape','sidewalk'],cues:['stop identifier','route information','boarding area'],exclusions:['tour pickup sign','taxi stand'],attributes:['shelter','bench','route_info','boarding_pad'],action:'Track amenities, information, boarding access, and route connection.',risk:'low'},
  {id:'boarding_area_obstruction',label:'Transit boarding obstruction',category:'transit_access',lens:'accessibility',aliases:['blocked bus stop','boarding pad obstruction','transit access blocked'],contexts:['transit','streetscape','sidewalk'],cues:['objects in boarding zone','curb access blocked','shelter entry obstructed'],exclusions:['waiting passengers','moving bus'],attributes:['obstruction_type','clear_area_m2','curb_access','duration_unknown'],action:'Clear the boarding area and maintain an accessible connection to the stop.',risk:'high'},
  {id:'shelter_damage',label:'Transit shelter damage',category:'transit_access',lens:'safety',aliases:['broken bus shelter','damaged shelter','shattered panel'],contexts:['transit','streetscape','sidewalk'],cues:['broken glazing','bent frame','loose roof panel','sharp fragments'],exclusions:['advertising panel change','normal weathering'],attributes:['damage_type','sharp_material','weather_protection_lost','structural_concern'],action:'Isolate sharp or unstable components and repair the shelter.',risk:'high'},
  {id:'curb_damage',label:'Damaged curb',category:'surface_condition',lens:'general',aliases:['broken curb','spalled kerb','curb deterioration'],contexts:['streetscape','intersection','sidewalk'],cues:['missing curb segment','spalling','cracked curb face'],exclusions:['intentional curb cut','drain opening'],attributes:['damage_type','length_m','height_loss_mm','drainage_effect'],action:'Repair the curb where drainage, delineation, or access is affected.',risk:'medium'},
  {id:'curb_color_marking',label:'Curb regulation marking',category:'curb_management',lens:'general',aliases:['painted curb','curb color','parking curb marking'],contexts:['streetscape','intersection','transit'],cues:['continuous curb paint','stenciled restriction','loading-zone color'],exclusions:['construction overspray','decorative band'],attributes:['color','visibility_percent','stencil_legible','segment_length_m'],action:'Verify meaning against local policy and renew worn markings.',risk:'low'},
  {id:'illegal_parking_indicator',label:'Possible parking obstruction',category:'curb_management',lens:'safety',aliases:['blocked curb ramp','vehicle obstruction','parking violation'],contexts:['streetscape','intersection','sidewalk','transit'],cues:['vehicle overlaps crossing access','vehicle blocks loading or emergency zone','curb marking conflict'],exclusions:['moving vehicle','authorized emergency response'],attributes:['blocked_feature','vehicle_state_unknown','marking_visible','duration_unknown'],action:'Verify the condition in context before enforcement or escalation.',risk:'high'},
  {id:'road_debris',label:'Roadway debris',category:'surface_hazard',lens:'safety',aliases:['debris in road','fallen material','lane obstruction'],contexts:['streetscape','intersection','construction'],cues:['loose object in travel path','scattered material','impact remnants'],exclusions:['painted marking','embedded pavement patch'],attributes:['debris_type','lane_position','size_m','sharp_or_heavy'],action:'Remove the debris safely and investigate its source.',risk:'high'},
  {id:'fallen_branch',label:'Fallen branch',category:'surface_hazard',lens:'safety',aliases:['tree limb down','branch obstruction','storm debris'],contexts:greenContexts,cues:['detached woody limb','leafed branch on route','broken tree connection'],exclusions:['landscaping pile','small twig litter'],attributes:['diameter_cm','blocks_route','overhead_damage','utility_contact'],action:'Secure the area, check overhead hazards, and remove the branch.',risk:'high'},
  {id:'snow_or_ice',label:'Snow or ice accumulation',category:'weather_hazard',lens:'safety',aliases:['icy sidewalk','snow blocked path','frozen surface'],contexts:streetContexts,cues:['snow cover','ice sheen','plow ridge','untreated route'],exclusions:['salt residue','wet reflective paving'],attributes:['coverage_percent','estimated_depth_cm','treated','blocks_route'],action:'Treat and clear the route according to the applicable weather plan.',risk:'high'},
  {id:'heat_exposure',label:'Unshaded heat-exposed route',category:'climate_resilience',lens:'environment',aliases:['no shade','heat exposure','sun-exposed sidewalk'],contexts:['streetscape','sidewalk','park','transit'],cues:['long route without canopy','high solar exposure','dark paving'],exclusions:['short isolated gap','capture in low sun only'],attributes:['unshaded_length_m','canopy_percent','rest_area_nearby','surface_tone'],action:'Evaluate shade, rest points, materials, and heat mitigation opportunities.',risk:'medium'},
  {id:'flood_marker',label:'Flood level evidence',category:'climate_resilience',lens:'environment',aliases:['high water mark','flood debris line','inundation evidence'],contexts:['waterfront','streetscape','park','building_edge'],cues:['debris line','water staining','mud line','inundated route'],exclusions:['routine cleaning line','decorative material transition'],attributes:['estimated_height_m','affected_area','recency','corroboration'],action:'Document extent, validate timing, and update resilience planning records.',risk:'high'},
  {id:'shoreline_erosion',label:'Shoreline erosion',category:'climate_resilience',lens:'environment',aliases:['bank erosion','waterfront scour','edge loss'],contexts:['waterfront','park'],cues:['undercut bank','exposed roots','collapsed edge','fresh sediment'],exclusions:['designed stepped edge','natural stable rock'],attributes:['length_m','retreat_m','active_scour','public_route_threat'],action:'Arrange a site assessment and prioritize protection of public routes.',risk:'high'},
  {id:'public_art',label:'Public art asset',category:'civic_asset',lens:'general',aliases:['mural','sculpture','art installation'],contexts:['streetscape','sidewalk','park','waterfront','building_edge'],cues:['purpose-built artwork','interpretive plaque','civic installation'],exclusions:['advertisement','graffiti without authorization'],attributes:['asset_type','condition','plaque_present','surface_damage'],action:'Maintain a traceable condition history without classifying authorized art as damage.',risk:'low'},
  {id:'water_feature',label:'Public water feature',category:'civic_asset',lens:'environment',aliases:['fountain','splash feature','reflecting pool'],contexts:['park','waterfront','building_edge'],cues:['designed basin','recirculating jets','public feature edge'],exclusions:['stormwater ponding','natural water body'],attributes:['operating','water_clarity','edge_condition','barrier_needed_unknown'],action:'Track operation, water condition, edge safety, and maintenance signals.',risk:'low'},
  {id:'animal_waste',label:'Animal waste on route',category:'cleanliness',lens:'environment',aliases:['pet waste','dog waste','fecal contamination'],contexts:['sidewalk','park','waterfront','streetscape'],cues:['localized organic waste on walking surface','repeated deposits'],exclusions:['soil clump','leaf litter'],attributes:['count','route_position','near_play_area','bag_station_nearby'],action:'Remove contamination and review waste-station coverage where recurring.',risk:'medium'},
  {id:'pest_indicator',label:'Pest activity indicator',category:'public_health',lens:'environment',aliases:['rodent evidence','pest burrow','vermin indicator'],contexts:['streetscape','park','waterfront','building_edge'],cues:['burrow opening','gnawing','droppings cluster','repeated sightings'],exclusions:['irrigation opening','normal wildlife habitat away from public use'],attributes:['indicator_type','count','food_source_nearby','public_contact_risk'],action:'Confirm evidence and coordinate sanitation and pest-management response.',risk:'medium'},
  {id:'encampment_indicator',label:'Occupied public-space indicator',category:'human_context',lens:'general',aliases:['temporary shelter','personal belongings cluster','occupied area'],contexts:['streetscape','park','waterfront','transit','building_edge'],cues:['shelter materials','personal belongings','sleeping setup'],exclusions:['event setup','construction storage'],attributes:['route_impact','immediate_hazard','services_needed_unknown','privacy_sensitive'],action:'Apply privacy-preserving review and follow humane local outreach protocols.',risk:'low'},
  {id:'crowding',label:'Pedestrian crowding',category:'human_context',lens:'general',aliases:['crowded walkway','pedestrian congestion','high foot traffic'],contexts:['sidewalk','intersection','transit','park'],cues:['dense pedestrian flow','queue spills into route','restricted passing'],exclusions:['single-frame perspective overlap','organized event with controls'],attributes:['density_band','queue_present','route_width_m','time_pattern_unknown'],action:'Corroborate across time before planning operational changes.',risk:'medium'},
  {id:'delivery_obstruction',label:'Delivery activity obstruction',category:'curb_management',lens:'accessibility',aliases:['loading obstruction','packages on sidewalk','delivery cart blocking'],contexts:['streetscape','sidewalk','building_edge'],cues:['hand truck in route','packages staged on walkway','loading crosses path'],exclusions:['brief moving delivery worker','designated loading area outside route'],attributes:['obstruction_type','clear_width_m','duration_unknown','alternative_path'],action:'Preserve a continuous clear route during loading operations.',risk:'medium'},
  {id:'outdoor_dining_intrusion',label:'Outdoor dining route intrusion',category:'sidewalk_management',lens:'accessibility',aliases:['tables block sidewalk','café obstruction','dining encroachment'],contexts:['sidewalk','streetscape','building_edge'],cues:['tables or chairs narrow route','queue at dining edge','planter boundary intrusion'],exclusions:['furniture fully inside permitted zone','temporarily moving chair'],attributes:['clear_width_m','boundary_present','queue_impact','accessible_table'],action:'Verify the permitted layout and restore the required continuous route.',risk:'high'},
  {id:'sandwich_board',label:'Portable sidewalk sign',category:'sidewalk_management',lens:'accessibility',aliases:['a-frame sign','sandwich board','portable advertisement'],contexts:['sidewalk','streetscape','building_edge'],cues:['folding sign in pedestrian area','freestanding advertising panel'],exclusions:['official temporary warning sign','fixed wayfinding'],attributes:['clear_width_m','cane_detectable','placement_zone','wind_stable'],action:'Relocate the sign to maintain a predictable, detectable clear route.',risk:'medium'},
  {id:'awning_clearance',label:'Low awning or projection',category:'overhead_clearance',lens:'accessibility',aliases:['low canopy','head-height obstruction','low projection'],contexts:['sidewalk','building_edge','transit'],cues:['object projects into route overhead','low hanging sign','collapsed awning'],exclusions:['high canopy','tree canopy above clearance'],attributes:['estimated_clearance_m','projection_type','route_position','detectable_below'],action:'Measure clearance and remove, raise, or guard the projection.',risk:'high'},
  {id:'low_branch',label:'Low tree branch',category:'overhead_clearance',lens:'accessibility',aliases:['branch over sidewalk','low limb','head-height branch'],contexts:greenContexts,cues:['branch crosses route below canopy','visible pedestrian conflict'],exclusions:['high canopy','branch outside travel route'],attributes:['estimated_clearance_m','branch_diameter_cm','route_coverage','tree_health'],action:'Prune using arboricultural practice while preserving tree health.',risk:'medium'},
  {id:'door_swing_conflict',label:'Door swing route conflict',category:'building_interface',lens:'accessibility',aliases:['door opens onto sidewalk','egress door conflict','swing obstruction'],contexts:['building_edge','sidewalk','transit'],cues:['door leaf enters pedestrian path','swing arc conflicts with route'],exclusions:['recessed doorway','sliding door'],attributes:['swing_direction','route_width_m','warning_present','door_state'],action:'Assess operational controls or physical changes to eliminate the conflict.',risk:'medium'},
  {id:'façade_spall',label:'Façade material spall',category:'building_interface',lens:'safety',aliases:['falling masonry','concrete spall','loose façade'],contexts:['building_edge','sidewalk','streetscape'],cues:['missing surface fragment','exposed reinforcement','debris below façade'],exclusions:['intentional textured finish','old patched area without active distress'],attributes:['height_m','area_m2','debris_present','active_cracking'],action:'Protect the fall zone and arrange an urgent façade inspection.',risk:'critical'},
  {id:'water_leak',label:'Visible water leak',category:'building_interface',lens:'environment',aliases:['pipe leak','irrigation leak','water discharge'],contexts:['building_edge','sidewalk','park','streetscape'],cues:['active flow from fixture','persistent wet trail','spray outside intended area'],exclusions:['recent rain runoff','planned irrigation pattern'],attributes:['source','flow_band','route_impact','drain_connection'],action:'Confirm the source, stop avoidable loss, and repair the system.',risk:'medium'},
  {id:'smoke_or_steam',label:'Smoke or steam plume',category:'air_quality',lens:'environment',aliases:['visible emissions','smoke plume','steam release'],contexts:['building_edge','construction','streetscape','transit'],cues:['localized airborne plume','source point','drifting opacity'],exclusions:['cloud or fog','vehicle exhaust in cold air'],attributes:['color','density','source','persistent_unknown'],action:'Corroborate the source and escalate when fire or hazardous emissions are possible.',risk:'critical'},
  {id:'dust_plume',label:'Construction dust plume',category:'air_quality',lens:'environment',aliases:['dust cloud','airborne construction dust','demolition dust'],contexts:['construction','streetscape','building_edge'],cues:['particulate cloud near work','dust leaving site boundary','dry cutting source'],exclusions:['fog','vehicle exhaust','lens flare'],attributes:['source_activity','crosses_boundary','suppression_visible','density_band'],action:'Pause uncontrolled dust generation and restore effective suppression.',risk:'high'},
  {id:'noise_source',label:'Persistent noise source',category:'soundscape',lens:'environment',aliases:['loud equipment','continuous noise','noise nuisance'],contexts:['construction','streetscape','park','transit','building_edge'],cues:['audio energy sustained over time','identifiable mechanical source','speech interference'],exclusions:['brief horn','single transient impact'],attributes:['source','duration_seconds','relative_level','time_context'],action:'Measure sound level and duration before determining mitigation.',risk:'medium'},
]

const profiles: Array<{id:PolicyProfile; accept:number; review:number; suppress:number; alwaysReview:boolean; description:string}> = [
  {id:'balanced',accept:.88,review:.68,suppress:.36,alwaysReview:false,description:'Balances recall and reviewer workload for routine field operations.'},
  {id:'risk_sensitive',accept:.93,review:.78,suppress:.28,alwaysReview:true,description:'Prioritizes human oversight when missed hazards have high consequences.'},
  {id:'high_precision',accept:.95,review:.82,suppress:.55,alwaysReview:false,description:'Returns fewer findings with stronger visual and temporal support.'},
  {id:'rapid_screen',accept:.80,review:.56,suppress:.24,alwaysReview:false,description:'Surfaces broad candidates for a fast first-pass field screen.'},
]

const temporalModes: TemporalMode[] = ['single_capture','change_detection']
const commonFields: ObservationFieldDefinition[] = [
  {key:'condition',label:'Condition',type:'string',required:true,description:'Concise visible condition grounded in the source evidence.'},
  {key:'location_hint',label:'Location hint',type:'string',required:true,description:'Stable relative location within the scene without inferring an address.'},
  {key:'occlusion',label:'Occlusion',type:'enum',required:true,description:'How much of the subject is visually obscured.',enumValues:['none','partial','substantial','unknown']},
  {key:'lighting',label:'Lighting',type:'enum',required:true,description:'Lighting context affecting visual confidence.',enumValues:['daylight','low_light','artificial','mixed','unknown']},
  {key:'estimated_extent',label:'Estimated extent',type:'string',required:false,description:'Conservative visual estimate with an explicit unit where possible.'},
]

function fieldForAttribute(attribute:string):ObservationFieldDefinition {
  const numeric = /(_m|_m2|_mm|_cm|_percent|_count|_deg|_seconds)$/.test(attribute) || ['count','capacity','heads_observed','step_count','occupied_count'].includes(attribute)
  const boolean = /^(is_|has_|blocks_|.*_present$|.*_visible$|.*_damaged$|.*_stable$|.*_loose$|.*_aligned$|.*_obstructed$|.*_guarded$|.*_treated$|.*_anchored$|.*_operating$|.*_continuous$|.*_corroborated$)/.test(attribute)
  return {
    key:attribute,
    label:attribute.replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase()),
    type:boolean?'boolean':numeric?'number':'string',
    required:false,
    description:`Observed ${attribute.replaceAll('_',' ')} for this concept; use null rather than guessing when evidence is insufficient.`,
    ...(attribute.endsWith('_m')?{unit:'m'}:attribute.endsWith('_m2')?{unit:'m²'}:attribute.endsWith('_mm')?{unit:'mm'}:attribute.endsWith('_cm')?{unit:'cm'}:attribute.endsWith('_percent')?{unit:'percent'}:{}),
  }
}

function buildRule(concept:ConceptSeed, profile:typeof profiles[number], temporalMode:TemporalMode):ObservationKnowledgeRule {
  const highRisk = concept.risk === 'high' || concept.risk === 'critical'
  const id = `${concept.id}.${profile.id}.${temporalMode}`
  return {
    id,
    conceptId:concept.id,
    canonicalLabel:concept.id,
    displayLabel:concept.label,
    category:concept.category,
    lensId:concept.lens,
    profile:profile.id,
    temporalMode,
    summary:`${concept.label} detection using the ${profile.id.replaceAll('_',' ')} policy in ${temporalMode.replaceAll('_',' ')} mode. ${profile.description}`,
    aliases:concept.aliases,
    negativeAliases:concept.exclusions,
    captureContexts:concept.contexts,
    modalities:concept.id==='noise_source'?['audio','video']:['image','video'],
    promptInstructions:[
      `Identify ${concept.label.toLowerCase()} only when at least one positive visual cue is visible.`,
      'Ground every assertion in an evidence region or timestamp and state uncertainty explicitly.',
      'Do not infer legal compliance, ownership, intent, identity, or measurements that are not visibly supported.',
      temporalMode==='change_detection'?'Compare stable scene entities across captures before assigning a change kind.':'Treat the capture as a point-in-time observation without inventing history.',
      highRisk?'Prefer a reviewable candidate over silent omission when a plausible high-consequence condition is visible.':'Suppress weak candidates that lack distinguishing evidence.',
    ],
    visualCues:concept.cues,
    exclusionCues:concept.exclusions,
    fields:[...commonFields,...concept.attributes.map(fieldForAttribute)],
    confidence:{
      autoAcceptAt:profile.accept,
      requireReviewBelow:profile.review,
      suppressBelow:profile.suppress,
      corroborationBonus:profile.id==='high_precision'?.025:.04,
      temporalAgreementBonus:temporalMode==='change_detection'?.06:.02,
      contradictionPenalty:highRisk?.24:.18,
    },
    review:{
      alwaysReview:profile.alwaysReview&&highRisk,
      reviewWhenSeverityAtLeast:highRisk?'high':'critical',
      reviewWhenStateIs:['review'],
      reviewWhenAttributesMissing:highRisk?['condition','location_hint']:['condition'],
      reviewerQuestions:[
        `Does the evidence visibly support the label “${concept.label}”?`,
        'Is the marked region or timestamp attached to the correct physical subject?',
        'Could perspective, lighting, occlusion, or a listed exclusion explain the appearance?',
        temporalMode==='change_detection'?'Are the compared observations linked to the same persistent entity?':'Is the point-in-time condition described without implying an unobserved change?',
      ],
      rejectionReasons:['wrong_subject','insufficient_evidence','listed_exclusion','duplicate_finding','perspective_or_lighting_artifact','unsupported_inference'],
    },
    temporal:{
      mode:temporalMode,
      minimumGapSeconds:temporalMode==='change_detection'?60:0,
      maximumGapSeconds:temporalMode==='change_detection'?31_536_000:undefined,
      stableAttributes:['canonical_label','scene_relative_location','persistent_geometry'],
      mutableAttributes:['condition','severity',...concept.attributes],
      changeKinds:temporalMode==='change_detection'?['appeared','disappeared','modified','moved','unchanged']:['unchanged'],
      meaningfulChangeWhen:[
        'severity increases by at least one band',
        'a previously clear public route becomes obstructed',
        'the subject appears, disappears, or moves beyond the configured spatial tolerance',
        'a required safety or accessibility attribute changes materially',
      ],
    },
    severityBands:[
      {severity:'low',when:'The condition is visible but does not presently restrict a route or create an immediate hazard.',rationale:'Record for condition history and routine maintenance.'},
      {severity:'medium',when:'The condition reduces usability, visibility, or resilience but an adequate alternative remains.',rationale:'Prioritize for planned inspection or maintenance.'},
      {severity:'high',when:'The condition materially restricts access, creates a credible injury risk, or threatens critical function.',rationale:'Requires prompt human review and response planning.'},
      {severity:'critical',when:'The evidence suggests immediate danger, emergency-access loss, major fall/electrical exposure, or active hazardous discharge.',rationale:'Escalate immediately while preserving uncertainty and evidence.'},
    ],
    searchTerms:[concept.label,concept.id.replaceAll('_',' '),concept.category.replaceAll('_',' '),...concept.aliases,...concept.cues],
    recommendedActions:[concept.action,'Verify the finding in context before any enforcement or irreversible action.','Preserve the original media and record the reviewer decision in the provenance chain.'],
    evidenceRequirements:['At least one source asset with an immutable fingerprint.','A normalized region, frame timestamp, or transcript segment binding.','Capture time and scene identity.','Model name, policy rule, and confidence score.'],
    provenanceRequirements:['Original asset fingerprint','Analysis request and model version','Knowledge rule identifier','Human review decision when required','Parent link for every derived or generated output'],
    advisoryNotice:'This rule is an operational evidence aid, not a legal code determination. Validate measurements and jurisdiction-specific requirements independently.',
  }
}

const rules = concepts.flatMap(concept => profiles.flatMap(profile => temporalModes.map(mode => buildRule(concept,profile,mode))))
const catalog:ObservationKnowledgeCatalog = {
  metadata:{
    schemaVersion:'1.0.0',
    catalogVersion:'2026.09.23',
    title:'Scenara Urban Evidence Knowledge Catalog',
    description:'Configurable observation, confidence, review, temporal, and provenance policies for multimodal field-scene intelligence.',
    generatedAt:'2026-09-23T00:00:00.000Z',
    disclaimer:'Advisory operational catalog. It does not assert legal compliance and must be paired with local standards and qualified review.',
    ruleCount:rules.length,
    conceptCount:concepts.length,
    profiles:profiles.map(item=>item.id),
    temporalModes,
  },
  rules,
}

const outputPath=resolve(process.cwd(),'knowledge','observation-catalog.json')
await mkdir(dirname(outputPath),{recursive:true})
await writeFile(outputPath,`${JSON.stringify(catalog,null,2)}\n`,'utf8')
console.log(`Generated ${rules.length} evidence rules from ${concepts.length} concepts at ${outputPath}`)
